name: 'Dhall Actions'
description: 'A couple of actions for checking dhall files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dhallVersion }}

inputs:
  dhallVersion:
    required: false
    default: '1.39.0'
    description: |
      Version of dhall-haskell to use.

      Should be a tag from https://github.com/dhall-lang/dhall-haskell.

  typecheck_no_cache:
    required: false
    default: false
    description: |
      Whether to pass `--no-cache` when typechecking.

      Having this set to `false` (meaning: caching enabled) can greatly speed
      up checking as the number of files to check increases. However, doing so
      can also lead to some unpredictability, as caching in general can be
      known to do.

  typecheck_package_files_only:
    required: false
    default: false
    description: |
      Whether to only typecheck `package.dhall` files (as opposed to `*.dhall`.

      The thought here is that checking `package.dhall` is likely to
      transitively check all other `*.dhall`, so it should be sufficient while
      avoiding lots of duplicated work. However, this is certainly not always
      the case, so consider that when setting this input to `true`.
