-- This file is automatically generated; please, do not edit it manually
{ dhallVersion = ./dhallVersion/package.dhall
, errorOnFreezeDiff = ./errorOnFreezeDiff/package.dhall
, typecheck_no_cache = ./typecheck_no_cache/package.dhall
, typecheck_package_files_only = ./typecheck_package_files_only/package.dhall
}
