-- This file is automatically generated; please, do not edit it manually
{ default = ./default.dhall ? (../imports.dhall).JSON.null
, deprecationMessage = Some ./deprecationMessage.txt as Text ? None Text
, description = ./description.txt as Text
, required = ./required.dhall
}
