name: CI
on: [push]
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.1.0

  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: awseward/gh-actions-shell@0.1.0
